version: '3.7'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
    restart: always
    ports:
      - 8000:80
    expose:
      - 80
  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./mysql:/var/lib/mysql
volumes:
  api:
  mysql: