version: '3.7'
services:
    php:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: php 
        depends_on:
            - database
        volumes:
            - ./app:/var/www/html
        restart: always
        ports:
            - 8000:80
    database:
        image: mysql:5.7
        container_name: mysql
        restart: always
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        expose:
            - 3306
        volumes:
            - ./mysql:/var/lib/mysql
volumes:
    php:
    mysql: