#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_graphql_entrypoint:
    path: /api/graphql
    controller: api_platform.graphql.action.entrypoint
graphiql:
    path: /docs/graphiql
    controller: api_platform.graphql.action.graphiql
graphql_playground:
    path: /docs/graphql_playground
    controller: api_platform.graphql.action.graphql_playground