doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    # Connection to use for the migrations
#    connection: kioskito

    # Entity manager to use for migrations. This overrides the "connection" setting.
    em: customer
